### ISSUE TITLE
Noesis Python Error

### ISSUE THREAD

**Issue by DiHubKi** [widberg/fmt_fuel#1]
![image](https://user-images.githubusercontent.com/53359732/219939625-ad19a1e8-c58a-4ccf-b53f-d1bacb28a202.png)

Error on everything

**Comment by widberg** [comment]
This is for FUEL. The format in WALL-E is different. You can try https://github.com/SamuraiOndo/various-noesis-plugins/blob/main/asobo_bitmap_z.py

**Comment by Disa-Kizonda** [comment]
Now it's working but not completely. How can I try to fix it if I don't have much knowledge about it
![image](https://user-images.githubusercontent.com/53359732/219988295-a0a5e107-4949-4e4a-8196-85cb908f40f1.png)

**Comment by widberg** [comment]
I recommend joining the discord https://discord.gg/CQgMNbYeUR or opening an issue on the repository with that script. Since I did not author it I also don't know what could be wrong.
